version: '3.8'

services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.6.2
    container_name: es01
    environment:
      - node.name=es01
      - discovery.type=single-node
      - cluster.name=docker-cluster
      - path.data=/usr/share/elasticsearch/data
      - path.logs=/usr/share/elasticsearch/logs
      - ES_JAVA_OPTS=-Xms2g -Xmx2g
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata01:/usr/share/elasticsearch/data
      - eslog01:/usr/share/elasticsearch/logs
    ports:
      - 9200:9200
    networks:
      - elk-network

  kibana:
    image: docker.elastic.co/kibana/kibana:8.6.2
    container_name: kibana
    ports:
      - 5601:5601
    expose:
      - "5601"
    volumes:
      - ./kibana/kibana.yml:/usr/share/kibana/config/kibana.yml:ro
    networks:
      - elk-network

  logstash:
    image: docker.elastic.co/logstash/logstash:8.6.2
    container_name: logstash
    environment:
      - "LS_PIPELINE_WORKERS=8"
      - "LS_PIPELINE_BATCH_SIZE=125"
      - "LS_HTTP_HOST=0.0.0.0"
      - "LS_CONFIG_RELOAD_AUTOMATIC=true"
      - "XPACK_MONITORING_ENABLED=false"
      - "LS_JAVA_OPTS=-Xmx512m -Xms512m"
    volumes:
      - ./logstash/logstash-filebeat.conf:/usr/share/logstash/pipeline/logstash-filebeat.conf:ro
      - ./logstash/logstash-metricbeat.conf:/usr/share/logstash/pipeline/logstash-metricbeat.conf:ro
    ports:
      - 5044:5044
      - 9601:9601
    networks:
      - elk-network
    depends_on:
      - es01

  filebeat:
    image: docker.elastic.co/beats/filebeat:8.6.2
    container_name: filebeat
    volumes:
      - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - ./filebeat/logs:/usr/share/filebeat/logs:rw
    networks:
      - elk-network
    depends_on:
      - logstash

  metricbeat:
    image: docker.elastic.co/beats/metricbeat:8.6.2
    container_name: metricbeat
    network_mode: "host"
    user: root
    volumes:
      - ./metricbeat/metricbeat.yml:/usr/share/metricbeat/metricbeat.yml:ro
      - /sys/fs/cgroup:/hostfs/sys/fs/cgroup:ro
      - /proc:/hostfs/proc:ro
      - /:/hostfs:ro
    depends_on:
      - logstash

volumes:
  esdata01:
    driver: local
  eslog01:
    driver: local

networks:
  elk-network:
    driver: bridge
